"use client"

import { useState } from "react"
import { historicalSignals } from "@/lib/market-data"
import { agents } from "@/lib/agents"
import { cn } from "@/lib/utils"
import {
  CheckCircle2,
  XCircle,
  Clock,
  AlertCircle,
  Filter,
  Search,
} from "lucide-react"

type FilterStatus = "all" | "active" | "closed" | "expired"
type FilterDecision = "all" | "BUY" | "SELL" | "HOLD"

export default function SignalsPage() {
  const [statusFilter, setStatusFilter] = useState<FilterStatus>("all")
  const [decisionFilter, setDecisionFilter] = useState<FilterDecision>("all")
  const [searchQuery, setSearchQuery] = useState("")

  const filteredSignals = historicalSignals.filter((signal) => {
    const matchesStatus =
      statusFilter === "all" || signal.status === statusFilter
    const matchesDecision =
      decisionFilter === "all" || signal.decision === decisionFilter
    const matchesSearch =
      signal.pair.toLowerCase().includes(searchQuery.toLowerCase()) ||
      signal.reasoning.toLowerCase().includes(searchQuery.toLowerCase())

    return matchesStatus && matchesDecision && matchesSearch
  })

  const getStatusIcon = (status: string, outcome?: string) => {
    if (status === "active") {
      return <Clock className="h-4 w-4 text-secondary" />
    }
    if (status === "expired") {
      return <AlertCircle className="h-4 w-4 text-muted-foreground" />
    }
    if (outcome === "profit") {
      return <CheckCircle2 className="h-4 w-4 text-accent" />
    }
    if (outcome === "loss") {
      return <XCircle className="h-4 w-4 text-destructive" />
    }
    return <Clock className="h-4 w-4 text-muted-foreground" />
  }

  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp)
    return date.toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  const getAgentName = (agentId: string) => {
    const agent = agents.find((a) => a.id === agentId)
    return agent?.shortName || agentId
  }

  // Stats
  const totalSignals = historicalSignals.length
  const activeSignals = historicalSignals.filter(
    (s) => s.status === "active"
  ).length
  const profitableSignals = historicalSignals.filter(
    (s) => s.outcome === "profit"
  ).length
  const closedSignals = historicalSignals.filter(
    (s) => s.status === "closed"
  ).length
  const winRate = closedSignals > 0 
    ? Math.round((profitableSignals / closedSignals) * 100) 
    : 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-foreground">Signals Log</h1>
        <p className="mt-1 text-muted-foreground">
          Complete history of trading signals generated by the AI agents
        </p>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <div className="rounded-xl border border-border bg-card p-4 shadow-lg shadow-black/5">
          <p className="text-sm text-muted-foreground">Total Signals</p>
          <p className="mt-1 text-2xl font-bold text-card-foreground">
            {totalSignals}
          </p>
        </div>
        <div className="rounded-xl border border-border bg-card p-4 shadow-lg shadow-black/5">
          <p className="text-sm text-muted-foreground">Active Signals</p>
          <p className="mt-1 text-2xl font-bold text-secondary">
            {activeSignals}
          </p>
        </div>
        <div className="rounded-xl border border-border bg-card p-4 shadow-lg shadow-black/5">
          <p className="text-sm text-muted-foreground">Win Rate</p>
          <p className="mt-1 text-2xl font-bold text-accent">{winRate}%</p>
        </div>
        <div className="rounded-xl border border-border bg-card p-4 shadow-lg shadow-black/5">
          <p className="text-sm text-muted-foreground">Profitable</p>
          <p className="mt-1 text-2xl font-bold text-accent">
            {profitableSignals}/{closedSignals}
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-col gap-4 rounded-xl border border-border bg-card p-4 shadow-lg shadow-black/5 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2">
          <Filter className="h-4 w-4 text-muted-foreground" />
          <span className="text-sm font-medium text-card-foreground">
            Filters:
          </span>
        </div>

        {/* Search */}
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search by pair or reasoning..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full rounded-lg border border-border bg-muted/50 py-2 pl-10 pr-4 text-sm text-card-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
          />
        </div>

        {/* Status Filter */}
        <div className="flex gap-2">
          {(["all", "active", "closed", "expired"] as FilterStatus[]).map(
            (status) => (
              <button
                key={status}
                onClick={() => setStatusFilter(status)}
                className={cn(
                  "rounded-lg px-3 py-1.5 text-sm font-medium transition-colors",
                  statusFilter === status
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-muted/80"
                )}
              >
                {status.charAt(0).toUpperCase() + status.slice(1)}
              </button>
            )
          )}
        </div>

        {/* Decision Filter */}
        <div className="flex gap-2">
          {(["all", "BUY", "SELL", "HOLD"] as FilterDecision[]).map(
            (decision) => (
              <button
                key={decision}
                onClick={() => setDecisionFilter(decision)}
                className={cn(
                  "rounded-lg px-3 py-1.5 text-sm font-medium transition-colors",
                  decisionFilter === decision
                    ? decision === "BUY"
                      ? "bg-accent text-accent-foreground"
                      : decision === "SELL"
                        ? "bg-destructive text-destructive-foreground"
                        : "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-muted/80"
                )}
              >
                {decision === "all" ? "All Decisions" : decision}
              </button>
            )
          )}
        </div>
      </div>

      {/* Signals Table */}
      <div className="rounded-xl border border-border bg-card shadow-lg shadow-black/5">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-border bg-muted/30">
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Timestamp
                </th>
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Pair
                </th>
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Signal
                </th>
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Conviction
                </th>
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Contributing Agents
                </th>
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Reasoning
                </th>
                <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Status
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {filteredSignals.map((signal) => (
                <tr
                  key={signal.id}
                  className="transition-colors hover:bg-muted/20"
                >
                  <td className="whitespace-nowrap px-6 py-4 text-sm text-muted-foreground">
                    {formatTime(signal.timestamp)}
                  </td>
                  <td className="whitespace-nowrap px-6 py-4 text-sm font-semibold text-card-foreground">
                    {signal.pair}
                  </td>
                  <td className="whitespace-nowrap px-6 py-4">
                    <span
                      className={cn(
                        "inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold",
                        signal.decision === "BUY" &&
                          "bg-accent/10 text-accent",
                        signal.decision === "SELL" &&
                          "bg-destructive/10 text-destructive",
                        signal.decision === "HOLD" &&
                          "bg-muted text-muted-foreground"
                      )}
                    >
                      {signal.decision}
                    </span>
                  </td>
                  <td className="whitespace-nowrap px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="h-2 w-20 overflow-hidden rounded-full bg-muted">
                        <div
                          className={cn(
                            "h-full rounded-full",
                            signal.conviction > 0
                              ? "bg-accent"
                              : "bg-destructive"
                          )}
                          style={{
                            width: `${Math.abs(signal.conviction)}%`,
                          }}
                        />
                      </div>
                      <span
                        className={cn(
                          "text-sm font-bold",
                          signal.conviction > 0
                            ? "text-accent"
                            : "text-destructive"
                        )}
                      >
                        {signal.conviction > 0 ? "+" : ""}
                        {signal.conviction}
                      </span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex flex-wrap gap-1">
                      {signal.agents.map((agentId) => (
                        <span
                          key={agentId}
                          className="rounded-md bg-muted px-2 py-0.5 text-xs text-muted-foreground"
                        >
                          {getAgentName(agentId)}
                        </span>
                      ))}
                    </div>
                  </td>
                  <td className="max-w-xs px-6 py-4">
                    <p className="truncate text-sm text-muted-foreground">
                      {signal.reasoning}
                    </p>
                  </td>
                  <td className="whitespace-nowrap px-6 py-4">
                    <div className="flex items-center gap-2">
                      {getStatusIcon(signal.status, signal.outcome)}
                      <span className="text-sm capitalize text-muted-foreground">
                        {signal.outcome || signal.status}
                      </span>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filteredSignals.length === 0 && (
          <div className="px-6 py-12 text-center">
            <p className="text-muted-foreground">
              No signals match your filters.
            </p>
          </div>
        )}
      </div>

      {/* Integration Note */}
      <div className="rounded-lg border border-dashed border-border bg-muted/20 p-4">
        <p className="text-sm text-muted-foreground">
          {/* PLACEHOLDER: Real API integration would fetch paginated signal data from your backend */}
          <span className="font-medium text-card-foreground">Note:</span> This
          page displays simulated historical data. In production, signals would
          be fetched from your trading system database with pagination and
          real-time updates.
        </p>
      </div>
    </div>
  )
}
