"use client"

import { Sparkles, Lock } from "lucide-react"

export default function RecommendationsPage() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-[#060d1a] px-6 text-center">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(ellipse_60%_40%_at_50%_50%,rgba(56,108,255,0.06),transparent)]" />

      <div className="relative flex flex-col items-center gap-6">
        <div className="flex h-20 w-20 items-center justify-center rounded-2xl border border-primary/20 bg-primary/5">
          <Sparkles className="h-9 w-9 text-primary/60" />
        </div>

        <div>
          <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-[#334155]/60 bg-[#1e293b]/40 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
            <Lock className="h-3 w-3" />
            Coming Soon
          </div>
          <h1 className="mb-2 text-2xl font-black tracking-tight text-foreground">
            AI Recommendations
          </h1>
          <p className="max-w-sm text-sm leading-relaxed text-muted-foreground">
            Personalised trade recommendations generated by your five AI agents.
            Launching alongside the full platform.
          </p>
        </div>

        <div className="mt-2 flex items-center gap-2 rounded-xl border border-[#334155]/40 bg-[#1e293b]/30 px-5 py-3 text-xs text-muted-foreground">
          <div className="h-1.5 w-1.5 animate-pulse rounded-full bg-amber-400" />
          You are on the early access list
        </div>
      </div>
    </div>
  )
}